### ISSUE TITLE
Could this lib used for risingwave udf？

### ISSUE THREAD

**Issue by yfclark** [risingwavelabs/arrow-udf#3]
I'm researching risingwave's UDF and hoping to develop some UDFs based on Rust that can be parsed and used by risingwave's SQL. I'm glad to see this project and also see that you are a developer related to risingwave. I'd like to ask if it's possible to couple this project with developing UDFs in Rust language for risingwave? My idea is to develop a function that is suitable for normal operations and also for aggregation under Windows like tumble or hop window. Thank you

**Comment by wangrunji0408** [comment]
Yes, this crate is primarily designed for RisingWave's Rust UDF. However, we deliberately decouple it from RisingWave, making it depend on arrow-rs only, so that other projects in Rust can reuse it.
If you are going to define Rust functions in RisingWave, please follow this [documentation](https://docs.risingwave.com/docs/dev/udf-rust/). Currently we only support scalar functions and table functions, but not aggregate functions. We believe it can cover most use cases. Could you elaborate more on the functions you want to develop? Thanks!
