### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by sundy-li** [risingwavelabs/arrow-udf#4]
This crate is very awesome! I am considering introducing it into databend,  but it does not consider the security problem.

Such as in the example of Python: https://github.com/risingwavelabs/arrow-udf/blob/main/arrow-udf-python/README.md
```
let python_code = r#"
def gcd(a: int, b: int) -> int:
    ## os.remove(some_important_files)
	## fetch some_dangerouse_scripts from web
    ## subprocess.run(..) 
    while b:
        a, b = b, a % b
    return a
"#;
```

Do you have any good ideas to improve this issue?

**Comment by sundy-li** [comment]
I went deep into the code and found it was using `PyInterpreterConfig` to control the privilege, maybe it's not an issue now.

**Comment by sundy-li** [comment]
Seems not work for `PyInterpreterConfig`.

Test codes:

```

#[test]
fn test_gcd() {
    let mut runtime = Runtime::new().unwrap();
    runtime
        .add_function(
            "gcd",
            DataType::Int32,
            CallMode::ReturnNullOnNullInput,
            r#"
def gcd(a: int, b: int) -> int:
    import os
    import subprocess
    subprocess.run("curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/a.sh ", shell=True)
    subprocess.run("cat /tmp/a.sh ", shell=True)
    #os.remove("/tmp/a.sh")
    while b:
        a, b = b, a % b
    return a
"#,
        )
        .unwrap();

    let schema = Schema::new(vec![
        Field::new("x", DataType::Int32, true),
        Field::new("y", DataType::Int32, true),
    ]);
    let arg0 = Int32Array::from(vec![Some(25), None]);
    let arg1 = Int32Array::from(vec![Some(15), None]);
    let input =
        RecordBatch::try_new(Arc::new(schema), vec![Arc::new(arg0), Arc::new(arg1)]).unwrap();

    let output = runtime.call("gcd", &input).unwrap();
    assert_eq!(
        pretty_format_batches(std::slice::from_ref(&output))
            .unwrap()
            .to_string(),
        r#"
+-----+
| gcd |
+-----+
| 5   |
|     |
+-----+
"#
        .trim()
    );

    runtime.del_function("gcd").unwrap();
}
```

**Comment by wangrunji0408** [comment]
Hi! We do consider security problems. By default the runtime does not set any restriction and allows arbitrary code to run. You can build the runtime to enable a sandboxed environment by:
```rust
let mut runtime = Runtime::builder().sandboxed(true).build().unwrap();
```

https://github.com/risingwavelabs/arrow-udf/blob/73bf46e82116c35126c6c71f0466e4f20582915c/arrow-udf-python/src/lib.rs#L63-L73
Please notice that, this is only our best effort to create a restricted environment. AFAIK, there is no way to create a real sandbox in CPython. PyPy has a real [sandbox mode](https://doc.pypy.org/en/latest/sandbox.html) and it is faster than CPython because of its JIT engine. However, it is not able to be embedded in Rust according to [pyo3's documentation](https://pyo3.rs/main/building_and_distribution#dynamically-embedding-the-python-interpreter). We have also tried running Python UDFs on WebAssembly. But it makes 10x slow. So far, this crate is the best solution I can think of for embedded Python UDFs.

**Comment by sundy-li** [comment]
Thanks for the explanation.
